[workspace]
members = [
    "nervusdb-core",
    "nervusdb-temporal",
    "bindings/node/native/nervusdb-node",
    "bindings/uniffi/nervusdb-uniffi",
    "nervusdb-cli"
, "nervusdb-v2-storage"
, "nervusdb-v2"
, "nervusdb-v2-api"
]
resolver = "2"
