[package]
name = "nervusdb-v2"
version = "0.1.0"
edition = "2021"

[dependencies]
nervusdb-v2-api = { path = "../nervusdb-v2-api" }
nervusdb-v2-storage = { path = "../nervusdb-v2-storage" }
nervusdb-v2-query = { path = "../nervusdb-v2-query" }

[dev-dependencies]
tempfile = "3"
