[patch.crates-io]
nervusdb-v2-api = { path = "nervusdb-v2-api" }
nervusdb-v2-storage = { path = "nervusdb-v2-storage" }
nervusdb-v2-query = { path = "nervusdb-v2-query" }
nervusdb-v2 = { path = "nervusdb-v2" }
