[patch.crates-io]
nervusdb-api = { path = "nervusdb-api" }
nervusdb-storage = { path = "nervusdb-storage" }
nervusdb-query = { path = "nervusdb-query" }
nervusdb = { path = "nervusdb" }

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]
