[package]
name = "nervusdb-v2-storage"
version = "0.1.0"
edition = "2024"

[dependencies]
crc32fast = "1.5.0"
thiserror = "2.0"
nervusdb-v2-api = { path = "../nervusdb-v2-api" }

[dev-dependencies]
tempfile = "3"
