[package]
name = "nervusdb-v2-query"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
nervusdb-v2-api = { path = "../nervusdb-v2-api" }

[dev-dependencies]
tempfile = "3"
nervusdb-v2-storage = { path = "../nervusdb-v2-storage" }
