[package]
name = "nervusdb-cli"
version = "1.0.3"
edition = "2024"
license = "AGPL-3.0-only"
description = "NervusDB CLI (streaming Cypher)"
repository = "https://github.com/LuQing-Studio/nervusdb"
autobins = false

[[bin]]
name = "nervusdb"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
nervusdb-core = { version = "1.0.3", path = "../nervusdb-core" }
nervusdb-v2 = { path = "../nervusdb-v2" }
nervusdb-v2-api = { path = "../nervusdb-v2-api" }
nervusdb-v2-query = { path = "../nervusdb-v2-query" }
nervusdb-v2-storage = { path = "../nervusdb-v2-storage" }
serde_json = "1.0"
