[package]
name = "nervusdb-v2-api"
version = "2.0.0"
license = "AGPL-3.0-only"
description = "NervusDB v2 public API â€“ GraphStore trait and data types"
repository = "https://github.com/LuQing-Studio/nervusdb"
documentation = "https://docs.rs/nervusdb-v2-api"
edition = "2024"

[dependencies]

